language: python
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly
install:
  - pip3 install -r requirements_dev.txt
  - pip3 install -r requirements_prod.txt
  - pip3 install coverage codacy-coverage
script:
  - pytest
after_script:
  - coverage run test/*
  - coverage xml
  - python-codacy-coverage -r coverage.xml
